In [ ]:
import os
import numpy as np 
import cv2

In [ ]:
images_dir = '/home/xabierga/Projects/Kaggle/stanford-dogs-dataset/Images'
os.listdir('/home/xabierga/Projects/Kaggle/stanford-dogs-dataset/Images'+'/n02089078-black-and-tan_coonhound')


['n02089078_2684.jpg',
 'n02089078_52.jpg',
 'n02089078_302.jpg',
 'n02089078_80.jpg',
 'n02089078_3355.jpg',
 'n02089078_4065.jpg',
 'n02089078_2021.jpg',
 'n02089078_4098.jpg',
 'n02089078_682.jpg',
 'n02089078_183.jpg',
 'n02089078_3810.jpg',
 'n02089078_4024.jpg',
 'n02089078_176.jpg',
 'n02089078_782.jpg',
 'n02089078_188.jpg',
 'n02089078_2106.jpg',
 'n02089078_376.jpg',
 'n02089078_222.jpg',
 'n02089078_4.jpg',
 'n02089078_2225.jpg',
 'n02089078_3893.jpg',
 'n02089078_2801.jpg',
 'n02089078_2110.jpg',
 'n02089078_185.jpg',
 'n02089078_695.jpg',
 'n02089078_314.jpg',
 'n02089078_324.jpg',
 'n02089078_351.jpg',
 'n02089078_2753.jpg',
 'n02089078_933.jpg',
 'n02089078_2957.jpg',
 'n02089078_3532.jpg',
 'n02089078_3613.jpg',
 'n02089078_877.jpg',
 'n02089078_192.jpg',
 'n02089078_2574.jpg',
 'n02089078_111.jpg',
 'n02089078_3652.jpg',
 'n02089078_1951.jpg',
 'n02089078_2478.jpg',
 'n02089078_45.jpg',
 'n02089078_4186.jpg',
 'n02089078_3340.jpg',
 'n02089078_2227.jpg',
 'n02089078_12

In [ ]:
print(os.listdir(images_dir)[28])

In [ ]:
pixels = 100
rgb = 3
dim = (pixels, pixels)


In [ ]:
def parse_dir(image_address):
    dir_image = os.listdir(image_address)
    m = 0
    for race in dir_image:
        race_dir = os.listdir(image_address + '/' + race)
        for img in race_dir:
            m += 1
            
    tensor = np.zeros((m , pixels, pixels , rgb), dtype = np.uint8)
    
    return tensor , m

In [ ]:
def parse_img(img_route , dim):
    
    img = cv2.imread(img_route)
    dim = tuple(dim)
    img = cv2.resize(img, dim , interpolation = cv2.INTER_AREA)
    
    return img
    

In [ ]:
test_img = '/home/xabierga/Projects/Kaggle/stanford-dogs-dataset/Images/n02089078-black-and-tan_coonhound/n02089078_2684.jpg'

In [ ]:
new_test_ig = parse_img(test_img , dim)

In [ ]:
def fill_tensor(image_address , dim):

    dir_image = os.listdir(image_address)
    
    n = len(dir_image)
    
    tensor , m = parse_dir(image_address)
    print(m)
    
    Y = np.zeros((m , n) , dtype = np.uint8)
        
    img_counter = 0
    
    for j , race in enumerate(dir_image): 
        
        race_dir = os.listdir(image_address + '/' + race)
        
        factor = img_counter
        
        for i,img in enumerate(race_dir):
            
            tensor[i+factor] = parse_img(image_address + '/' + race + '/' + img , dim)
            #print(tensor[i+n*j])
            Y[img_counter][j] = 1
            
            img_counter += 1
            
            
    return tensor , Y

In [ ]:
IMG , Y = fill_tensor(images_dir , dim)

20580


In [ ]:
print(IMG[20500])

[[[124 122 156]
  [124 129 149]
  [237 235 237]
  ...
  [109 122 173]
  [199 202 228]
  [220 220 239]]

 [[167 160 169]
  [157 150 159]
  [210 205 198]
  ...
  [103 120 172]
  [197 201 228]
  [220 216 235]]

 [[219 170 145]
  [202 163 151]
  [217 182 150]
  ...
  [122 144 197]
  [208 212 241]
  [212 207 226]]

 ...

 [[151 155 160]
  [151 155 160]
  [152 156 161]
  ...
  [190 199 202]
  [163 168 174]
  [140 137 148]]

 [[153 155 164]
  [152 155 161]
  [151 155 159]
  ...
  [187 199 201]
  [179 190 192]
  [150 154 159]]

 [[154 156 165]
  [155 157 164]
  [154 157 161]
  ...
  [184 196 198]
  [183 195 197]
  [173 178 182]]]


In [ ]:
def shuffle_dog(img_tensor , y_classes): 
    shuffle_img = np.copy(img_tensor)
    shuffle_y = np.copy(y_classes)
    seed = 32 
    np.random.seed(seed)
    np.random.shuffle(shuffle_img)
    np.random.shuffle(shuffle_y)
    return shuffle_img , shuffle_y

In [ ]:
import random

def shuffle_dog(img_tensor , y_classes):
    
    c = list(zip(img_tensor, y_classes))

    random.shuffle(c)

    img_tensor, y_classes = zip(*c)
    
    return img_tensor , y_classes

In [ ]:
IMG_shuff , Y_shuff = shuffle_dog(IMG , Y)
#print(IMG_shuff[:10])
#print(IMG[:10])


In [ ]:
print(Y_shuff[26])
cv2.imshow('HelloWorld', IMG_shuff[26])
cv2.waitKey(0)
cv2.destroyWindow('HelloWorld')

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0]


In [ ]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Conv2D , Flatten , Dropout , MaxPooling2D , BatchNormalization
from tensorflow.keras.losses import categorical_crossentropy
from tensorflow.keras.optimizers import Adadelta

def __init__(self , batch , epochs , IMG_shuff , Y_shuff ):
        
        self.batch_size = batch 
        self.epochs = epochs
        self.X_train ,self.X_test , self.y_train , self.y_test = shuffle() 
        self.X_test = x_test
        self.y_train = y_train 
        self.y_test = y_test
        self.num_classes = 2
        self.model = Sequential()
        
    def add_layers(self):
        
        self.model.add(Conv2D(32 , (3,3) , activation = 'relu', input_shape=(80,80,3)))
        self.model.add(Conv2D(32 , (3,3) , activation = 'relu'))
        self.model.add(MaxPooling2D(pool_size = (2,2)))
        self.model.add(BatchNormalization(axis = -1))
        
        self.model.add(Conv2D(64 , (3,3) , activation ='relu'))
        self.model.add(Conv2D(64 , (3,3) , activation ='relu'))
        self.model.add(MaxPooling2D(pool_size = (2,2)))
        self.model.add(BatchNormalization(axis = -1))
        
        self.model.add(Conv2D(128 , (3,3) , activation = 'relu'))
        self.model.add(Conv2D(128 , (3,3) , activation = 'relu'))
        self.model.add(MaxPooling2D(pool_size = (2,2)))
        self.model.add(BatchNormalization(axis = -1))
        
        self.model.add(Conv2D(256 , (3,3) , activation = 'relu'))
        self.model.add(Conv2D(256 , (3,3) , activation = 'relu'))
        self.model.add(MaxPooling2D(pool_size = (2,2)))
        self.model.add(BatchNormalization(axis = -1))

        
        self.model.add(Flatten())
        self.model.add(Dense(500, activation='relu'))
        self.model.add(BatchNormalization(axis = -1))
        self.model.add(Dropout(.25))
        self.model.add(Dense(100, activation='relu'))
        self.model.add(BatchNormalization(axis = -1))
        self.model.add(Dropout(.125))
        self.model.add(Dense(20, activation='relu'))
        self.model.add(BatchNormalization(axis = -1))

        
        self.model.add(Dense(self.num_classes , activation = "softmax"))
        
        
    def compile_model(self , verbose = 1):
        
        self.model.compile(loss = 'categorical_crossentropy' , optimizer = Adadelta() , metrics = ['accuracy'])
        self.model.fit(self.X_train , self.y_train , batch_size = self.batch_size , epochs = self.epochs , verbose = verbose , validation_data = (self.X_test , self.y_test))
        
    def score(self , verbose = 0):
        
        score = self.model.evaluate(self.X_test , self.y_test , verbose = verbose)
        print("Test loss: " , score[0])
        print("Test accuracy: " , score[1])
        
